msg/urls.py
from . import views
from django.urls import path

app_name = 'msg'

urlpatterns = [
    path('',views.message_list,name='message_list'),
    path('message_create/', views.message_create, name="message_create")
]

portfolio_page/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='portfolio_page'
urlpatterns = [
    path('', views.index, name='homepage')
]

project1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('portfolio_page.urls')),
    path('message/', include('msg.urls'))
]

msg/models.py
from django.db import models

class Message(models.Model):
    submiter = models.CharField(max_length=50)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return "{} - {}".format(self.submiter, self.snipped_message())
    
    def snipped_message(self):
        if len(self.message) > 20 :
            return self.message[:20] + " ..."
        return self.message

portfolio_page/models.py
from django.db import models

# Create your models here.

msg/forms.py
from . import models
from django import forms

class CreateMessageForm(forms.Form):
    submiter = forms.CharField(widget=forms.TextInput(attrs={
            "class" : "fields",
            "required" : True,
            "placeholder":"Your Name"
             }), max_length=50)
    
    message = forms.CharField(widget=forms.Textarea(attrs={
            "class" : "fields",
            "required" : True,
            "placeholder":"Your Message Here"
             }), max_length=50)
    
    class Meta:
           model = models.Message

msg/views.py
from django.shortcuts import render, redirect
from .models import Message
from . import forms

def message_list(request):
    messages = Message.objects.all()
    message_form = forms.CreateMessageForm()
    response = {
        'msgs' : messages,
        'form' : message_form
    }
    return render(request, 'msg/message_list.html', response)

def message_create(request):
    message_form = forms.CreateMessageForm(request.POST)
    if request.method == "POST" and message_form.is_valid():
        Message.objects.create(
            submiter = message_form.cleaned_data['submiter'],
            message = message_form.cleaned_data['message']
        )
    return redirect('msg:message_list')

portfolio_page/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request,("portfolio_page/SBF_HARI_1.html"))

msg/templates/msg/message_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'msg:message_create' %}" method="POST">
        {% csrf_token %}
        <div>
            {% for field in form.visible_fields %}
                {{ field }}
            {% endfor %}
        </div>
        <button type="submit">Pencet</button>
    </form>
    {% for message in msgs %}
        <h6>{{ message.submiter }}</h6>
        <p>{{ message.message }}</p>
        <p>{{ message.created_at }}</p>
    {% endfor %}
</body>
</html>

portfolio_page/templates/portfolio_page/SBF_HARI_1.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<title>Tugas SBF Cuy!</title>
		<link rel="stylesheet" href="{% static 'portfolio_page/Tugas-SBF1.css' %}" >
	</head>

	<body class="background">
		<div>

			<div class="nav">
				<a class="a" href="#profile">About Me</a>
				<a class="b" href="#Hobi">My Hobby</a>
				<a class="c" href="#masterpiece">My Masterpiece</a>
				<a class="d" href="#contact">Contact Me!</a>
			</div>

			<div class="content">

				<div class="About" id="profile">
					<p><img src="{% static 'portfolio_page/profile.jpg' %}"></p>
					<h1>Biodata Singkat</h1>
					<h3>I am Luthfi Idrus</h3>
					<h4>I was born on December 16, 2000</h4>
				</div>

				<hr>

				<div class="Hobby" id="Hobi">
					<h1>Hobby</h1>
					<p><img src="{% static 'portfolio_page/Dota2Logo.png' %}" class="Dota"></p>
					<p><img src="{% static 'portfolio_page/photography.jpg' %}" class="photo"></p>
					<h6>Hobi gua adalah bermain game Dota dan Photography</h6>
				</div>

				<hr>

				<div class="Masterpiece" id="masterpiece">
					<h1>Amazing isn't it?</h1>
					<img src="{% static 'portfolio_page/Mobil1.jpg' %}" class="Mobil">
					<img src="{% static 'portfolio_page/Mobil2.jpg' %}" class="Mobil">
					<img src="{% static 'portfolio_page/Mobil3.jpg' %}" class="Mobil">
					<img src="{% static 'portfolio_page/Mobil4.jpg' %}" class="Mobil">
				</div>

				<hr>

				<div class="Kontak" id="contact">
					<div class="sosmed1">
						<p><strong>ID Line: <br> luth.</strong></p>
					</div>

					<div class="sosmed2">
						<p><strong>@luthfiidrus</strong></p>
					</div>
				</div>

			</div>

		</div>

	</body>
	

</html>